app/__init__.py
from flask import Flask
import random
from app.config import Config
from app.routes.main import app as main_blueprint

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    app.register_blueprint(main_blueprint)

    @app.template_filter('shuffle')
    def shuffle_filter(s):
        s = list(s)
        random.shuffle(s)
        return s

    return app

app/routes/__init__.py
# app/routes/__init__.py

# This file can be empty if no special initialization is needed
# It's used to mark the routes directory as a package

app/routes/main.py
import html
import requests
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
import random

app = Blueprint('main', __name__)



@app.route('/')
def home():
    return render_template('index.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/quiz', methods=['GET', 'POST'])
def quiz():
    if request.method == 'POST':
        num_questions = request.form.get('num_questions')

        session['questions'] = fetch_questions(int(num_questions))
        session['current_question_index'] = 0  # Initialize the question index
        session['user_answers'] = []
        return redirect(url_for('main.question'))

    return render_template('quiz.html')



@app.route('/question', methods=['GET', 'POST'])
def question():
    questions = session.get('questions')
    current_question_index = session.get('current_question_index')

    # check if user route to /question
    if questions is None or current_question_index is None or current_question_index >= len(questions):
        return redirect(url_for('main.home'))

    if request.method == 'POST':
        user_answer = request.form.get('answer')
        if user_answer:
            session['user_answers'].append(user_answer)
            session['current_question_index'] += 1  # Increment the index only after saving the answer
            if session['current_question_index'] >= len(questions):
                return redirect(url_for('main.result'))
            
        return redirect(url_for('main.question'))

    current_question = questions[current_question_index]
    options = current_question['incorrect_answers'] + [current_question['correct_answer']]
    options = list(map(html.unescape, options))
    random.shuffle(options)
    question = html.unescape(current_question['question'])
    question_number = current_question_index + 1
    total_questions = len(questions)
    print(current_question)
    return render_template('question.html', question=question, options=options, question_number=question_number, total_questions=total_questions)


@app.route('/result')
def result():
    questions = session.get('questions')
    user_answers = session.get('user_answers')

    if not questions or not user_answers:
        return redirect(url_for('main.home'))

    score = 0
    for question, user_answer in zip(questions, user_answers):
        correct_answer = html.unescape(question['correct_answer'])
        if user_answer == correct_answer:
            score += 1

    total_questions = len(questions)
  

    return render_template('result.html', score=score, total_questions=total_questions )


def fetch_questions(amount):
    api_url = f"https://opentdb.com/api.php?amount={amount}&category=18&type=multiple"
    response = requests.get(api_url)
    data = response.json()
    questions = data['results']
    for question in questions:
        question['correct_answer'] = html.unescape(question['correct_answer'])
        question['incorrect_answers'] = [html.unescape(ans) for ans in question['incorrect_answers']]
        question['question'] = html.unescape(question['question'])
    return questions


@app.route('/trivia', methods=['GET'])
def get_trivia():
    num_questions = request.args.get('num_questions', default=3)
    api_url = f"https://opentdb.com/api.php?amount={num_questions}&category=18&type=multiple"
    response = requests.get(api_url)

    if response.status_code == 200:
        data = response.json()
        return jsonify(data)
    else:
        return jsonify({"error": "Failed to fetch trivia questions"}), response.status_code

if __name__ == '__main__':
    app.run(debug=True)

app/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="d-grid gap-2 p-4 text-center">
        <h1 class="mb-4">About Trivia Quest</h1>

        <section id="overview">
            <h2>Overview</h2>
            <p>Trivia Quest is a web application that offers a fun and engaging way to test your knowledge in various topics. Whether you're interested in science, history, or pop culture, Trivia Quest provides a wide range of trivia questions to challenge and entertain you.</p>
        </section>

        <section id="team" class="mt-4">
            <h2>Founder & Developer</h2>
            <strong>Nukman Mukrami</strong>
            
        </section>
        <section id="contact" class="mt-4">
            <h2>Contact</h2>
            <p>Have questions or suggestions? We'd love to hear from you!</p>
            <p>Email: nukman.mukrami3@gmail.com</p>
        </section>

    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title>Trivia Quest | {% block title %}{% endblock %} </title>

      <!-- Bootstrap CSS from Bootswatch -->
      <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/vapor/bootstrap.min.css">

       <!-- Css file -->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

      <!-- Favicon -->
      <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon">

      <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon">
</head>
      
  </head>
  <body>
      <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
          <div class="container-fluid">
              <a class="navbar-brand" href="#">Trivia Quest</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarColor01">
                  <ul class="navbar-nav me-auto">
                      <li class="nav-item">
                          <a class="nav-link active" href="{{ url_for('main.home') }}">Home
                              <span class="visually-hidden">(current)</span>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                      </li>
                  </ul>
              </div>
          </div>
      </nav>

      <div class="d-flex justify-content-center align-items-center vh-100 container">
          <div class="p-5 bg-primary border rounded responsive-box">
              {% block content %}
              {% endblock %}
          </div>
      </div>

      <footer id="footer" class="bg-dark text-white text-center py-3 mt-auto">
          <div>
              <p class="mb-0">&copy; <span id="currentYear"></span> TriviaQuest. All rights reserved.</p>
          </div>
      </footer>

      <!-- JavaScript file -->
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

      <!-- Bootstrap Bundle (includes Popper.js) -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h2>Welcome to Trivia Quest</h2>
    <form method="POST" autocomplete="off" action="{{ url_for('main.quiz') }}">
        <label for="num_questions">Enter number of questions (1-50):</label>

        <input class="form-control me-sm-2 mt-3" type="number" id="num_questions" name="num_questions" min="1" max="50"required>

        <div class="d-grid gap-2 mt-4 center">
            <button type="submit" class="btn btn-lg btn-secondary" >Start Quiz</button>
          </div>
    </form>
{% endblock %}

app/templates/question.html
{% extends 'base.html' %}

{% block title %}Question {{ question_number }}{% endblock %}

{% block content %}
    <h2>Question {{ question_number }} of {{ total_questions }}</h2>
    <h3 class="text-align: justify;">{{ question }}</h3>
    <form method="POST" action="{{ url_for('main.question') }}">
        {% for option in options %}
            <input type="radio" name="answer" value="{{ option }}" required> {{ option }}<br>
        {% endfor %}

        <div class="d-grid gap-2 mt-4">
            <button type="submit" class="btn btn-lg btn-secondary">Next</button>
        </div>
    </form>
{% endblock %}

app/templates/result.html
{% extends 'base.html' %}

{% block title %}Result{% endblock %}

{% block content %}

    
    <div class="d-grid gap-2 p-4 text-center">
        <h2>Your Score is <br> {{ score }}/{{total_questions}}</h2>
        
            
        <a href="{{ url_for('main.home') }}" class="btn btn-lg btn-secondary">Play Again</a>
    </div>
    
{% endblock %}